### ISSUE TITLE
Where is the RetroArch core?

### ISSUE THREAD

**Issue by dogerizergaming** [Jakz/retro8#10] opened 2020-02-05 20:42 UTC
Where is the RetroArch core?

**Comment by gouchi** [comment] 2020-02-12 19:01
You can try for now by compiling it

```
git clone https://github.com/Jakz/retro8.git
cd retro8
make -j$(nproc)
```

then launch it using 

`retroarch -L ./retro8_libretro.so pico8-cartridge.p8 or pico8-cartridge.png`

**Comment by dogerizergaming** [comment] 2020-02-14 02:04
When will it be available for download for windows and others?

**Comment by gouchi** [comment] 2020-02-15 20:14
Please bear in mind it is still WIP. I tried to compile it using [MSYS2](http://docs.libretro.com/development/retroarch/compilation/windows/#environment-configuration) and it compiled minus an issue with [macro LOGD](https://github.com/Jakz/retro8/blob/master/src/common.h#L61-L63).

If you want to [test](https://transfer.sh/Fl4fv/retro8_libretro.dll), you can try with this [cartridge](https://raw.githubusercontent.com/Kartones/pico-8/master/squashy.p8)

`retroarch.exe -L retro8_libretro.dll squashy.p8`

**Comment by inactive123** [comment] 2020-09-21 05:04
Hi @Jakz , so I'm finally trying to use this core on RetroArch, and I remember that one of the earliest screenshots showed it running Celeste Classic. 

However, I tried downloading the code, naming the text as .p8, and loading it, but I just get a black screen -

https://www.lexaloffle.com/bbs/?tid=2145

Any ideas? Is there some compatibility list and download links for the games/demos that already work?

**Comment by inactive123** [comment] 2020-09-21 05:11
UPDATE: OK, I got something running by adding the lines to the top of .p8 -

> version 8
> __lua__


However, Celeste still doesn't look quite correct -

![image](https://user-images.githubusercontent.com/1075274/93734475-9d138a80-fbd9-11ea-99fc-4978442cad04.png)

Anything else I'm missing?

File I'm using is here -

https://gist.github.com/twinaphex/1783851c046e138b1449378340fee2c4

**Comment by lbrpdx** [comment] 2020-10-22 21:49
I'm having the same issue. I can run several demos as a libretro core, but no luck with a game yet. And, like @twinaphex, I need to add a header `version 8/__lua__` to run most .p8 files.

**Comment by Jakz** [comment] 2020-10-24 11:58
Hey! Sorry for late response but I've been a lot busy lately.

My version of Celeste is working fine both in png and p8 version so I need to compare it with the one you attached to understand where's the problem

@twinaphex I just realized the version you are using doesn't have any graphics or music. It's like the code copy-pasted from the editor but that hasn't been saved properly by the P8 application itself. It should contain raw data as in:

```
__gfx__
000000000000000000000000088888800000000000000000000000000000000000aaaaa0000aaa000000a0000007707770077700000060000000600000060000
000000000888888008888880888888880888888008888800000000000888888000a000a0000a0a000000a0000777777677777770000060000000600000060000
000000008888888888888888888ffff888888888888888800888888088f1ff1800a909a0000a0a000000a0007766666667767777000600000000600000060000
00000000888ffff8888ffff888f1ff18888ffff88ffff8808888888888fffff8009aaa900009a9000000a0007677766676666677000600000000600000060000
0000000088f1ff1888f1ff1808fffff088f1ff1881ff1f80888ffff888fffff80000a0000000a0000000a0000000000000000000000600000006000000006000
```

where did you get the file?

EIDT: I tried to open your version of Celeste with original P8 and I get "couldn't load indeed".

**Comment by lbrpdx** [comment] 2020-10-24 12:05
@twinaphex said earlier:
> I tried downloading the code, naming the text as .p8, and loading it, but I just get a black screen  https://www.lexaloffle.com/bbs/?tid=2145

I did the same (with the same result). Where did you get your Celeste version from, @Jakz ?

**Comment by Jakz** [comment] 2020-10-24 12:44
Ok, you can't do this because the code is lacking the data. You must click the narrow cart icon in the lower left corner of the game which is running directly on official lexaloffle page, it will open a PNG which is the actual game itself (PICO-8 supports embedding the game itself in its image). 

But I haven't been able to tell Retroarch to load PNG with my code (instead that the internal image viewer), although it's supported by retro8, so you should load that PNG with official PICO-8 app and save it as a p8. (or tell me how to allow RetroArch to "launch" PNG images with the core, which is actually a current bug)

I'll attach some games directly here so you can make your tests, these include Celeste:
[cartridges.zip](https://github.com/Jakz/retro8/files/5432890/cartridges.zip)

**Comment by lbrpdx** [comment] 2020-10-27 14:54
Thanks @Jakz - so the core problem is how to tell Retroarch to load the PNG as a data file for retro8. I tried disabling the internal image viewer with `builtin_imageviewer_enable = false` in retroarch .cfg options, but the cart still didn't load - the .png image is not displayed, but I only get a black screen. Not sure how to move forward.

**Comment by Jakz** [comment] 2020-10-27 21:23
@lbrpdx There was an issue on how the file was recognized as a PNG image. It's fixed in https://github.com/Jakz/retro8/commit/cf53a26a9e025444b9dfca26d1be753e3cfe32f8 so now it should work.

It looks like performance is subpar compared to SDL2 backend, which is strange since the code involved is mostly the same (rasterization code is really the same). Maybe it's an issue only on my machine though.

**Comment by lbrpdx** [comment] 2020-10-28 18:31
@Jakz Thank you do much! I can confirm it now works -- and I also confirm the performance is a bit sluggish compared to SDL2, not only on your machine.

**Comment by klundry** [comment] 2020-12-18 20:36
I have compiled this on my Odroid Go Advance and it is working on some carts but the sound is just a constant buzz instead of the intended game audio. Is anyone else experience the same?

**Comment by lbrpdx** [comment] 2020-12-18 21:12
With the last PR on audio, I experience the same.
I put a comment on https://github.com/Jakz/retro8/commit/2b59334a8dd751fd52acf76209c2c5356153e919#r44893921 11 days ago, but got no feedback. Try my proposed modification, audio on Odroid Go Advance should work better.

**Comment by klundry** [comment] 2020-12-18 21:52
@lbrpdx Thanks for the heads up. Changed it to 15 and recompiled and it is definitely less glitchy but I have no sound at all. Still better than before and I can at least play some games :).

**Comment by Jakz** [comment] 2020-12-18 23:44
> With the last PR on audio, I experience the same.
> I put a comment on [2b59334#r44893921](https://github.com/Jakz/retro8/commit/2b59334a8dd751fd52acf76209c2c5356153e919#r44893921) 11 days ago, but got no feedback. Try my proposed modification, audio on Odroid Go Advance should work better.

I've read your comment but it looks like an hack so I'm not going to merge it directly into the code base if we can't understand exactly why it should fix the issue.

**Comment by lbrpdx** [comment] 2020-12-18 23:47
It is hacky, but as stated in my original comment, I don't understand how the 60 in `SAMPLE_RATE / 60` was calculated either. Can you clarify this point?

**Comment by Jakz** [comment] 2020-12-18 23:49
This is the rationale behind the pull request: https://github.com/Jakz/retro8/pull/24#issue-524348351 which made sense to me.

Actually sound emulations is still quite unfinished in any case 😞

**Comment by Nine-H** [comment] 2021-05-03 14:26
hello, you can load a .png file with your core by loading the core first and then the content. I've tried this with a few on the version on the buildbot, and they all fail loading the luascript from the cart file.

that's the first line of the code in the cart, a header comment.

```
flatpak run org.libretro.RetroArch 
Error on luaL_loadString
[string "-- celeste2..."]:2012: unexpected symbol near '%'

Error on lua_pcall on init
attempt to call a string value
```

**Comment by theofficialgman** [comment] 2021-05-06 05:54
> Thanks @Jakz - so the core problem is how to tell Retroarch to load the PNG as a data file for retro8. I tried disabling the internal image viewer with `builtin_imageviewer_enable = false` in retroarch .cfg options, but the cart still didn't load - the .png image is not displayed, but I only get a black screen. Not sure how to move forward.

this is actually necessary to get loading directly from command line working @Nine-H 
you have to disable the built in image viewer

**Comment by theofficialgman** [comment] 2021-05-06 05:55
also, is celeste audio broken for anyone else (using the one from the zip linked earlier)
it plays the loading sound over and over again in a loop (and its not the only game with that problem)

**Comment by gouchi** [comment] 2022-03-15 08:18
@dogerizergaming @Jakz We can close this ticket as retro8 core is available from the core downloader in RetroArch.

Thank you.

**Closed as completed** 2022-03-15 11:28 UTC
